# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/call_tss.smk"
include: "rules/coverage.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/tss/TSS.bed",
        expand(
            "results/deeptools/coverage/{sample}_{direction}.bw",
            sample=samples.index,
            direction=["plus", "minus"],
        ),
        expand(
            "results/deeptools/5prime_coverage/{sample}_{direction}.bw",
            sample=samples.index,
            direction=["plus", "minus"],
        ),
    default_target: True
